# Generated by Django 3.1.3 on 2021-05-11 13:01

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in progress', 'in progress'), ('archived', 'archived')], default='in progress', max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='article',
            name='order',
            field=models.IntegerField(default=1000, null=True),
        ),
        migrations.AddField(
            model_name='newspaper',
            name='columns',
            field=models.CharField(choices=[('2', 2), ('3', 3), ('4', 4), ('5', 5)], default=3, max_length=1),
        ),
        migrations.AddField(
            model_name='newspaper',
            name='page_size',
            field=models.CharField(choices=[('broadsheet', 'Broadsheet - 600 x 750 mm (23.5" x 29.5")'), ('tabloid', 'Tabloid - 280 x 430 mm (11.0" x 16.9")'), ('berliner', 'Berliner - 315 x 470 mm (12.4" x 18.5")')], default='berliner', max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TypoTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in progress', 'in progress'), ('awaiting review', 'awaiting review'), ('confirmed', 'confirmed')], default='in progress', max_length=100)),
                ('articletask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.articletask')),
                ('assignee', models.ForeignKey(limit_choices_to={'groups__name': 'Head of typography'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TextTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in progress', 'in progress'), ('awaiting review', 'awaiting review'), ('confirmed', 'confirmed')], default='in progress', max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('author', models.CharField(max_length=50)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('articletask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.articletask')),
                ('assignee', models.ForeignKey(limit_choices_to={'groups__name': 'Author'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in progress', 'in progress'), ('awaiting review', 'awaiting review'), ('confirmed', 'confirmed')], default='in progress', max_length=100)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('articletask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.articletask')),
                ('assignee', models.ForeignKey(limit_choices_to={'groups__name': 'Illustrator'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='articletask',
            name='newspaper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.newspaper'),
        ),
        migrations.AddField(
            model_name='articletask',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Copy editor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AdTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in progress', 'in progress'), ('awaiting review', 'awaiting review'), ('confirmed', 'confirmed')], default='in progress', max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('articletask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.articletask')),
                ('assignee', models.ForeignKey(limit_choices_to={'groups__name': 'Advertisement designer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
