# Generated by Django 3.1.3 on 2021-05-15 02:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auto_20210512_0521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adtask',
            name='assignee',
        ),
        migrations.RemoveField(
            model_name='imagetask',
            name='assignee',
        ),
        migrations.RemoveField(
            model_name='texttask',
            name='assignee',
        ),
        migrations.RemoveField(
            model_name='typotask',
            name='assignee',
        ),
        migrations.AddField(
            model_name='basetask',
            name='assignee',
            field=models.ForeignKey(default=3, limit_choices_to={'groups__name': 'Illustrator'}, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='page_size',
            field=models.CharField(choices=[('berliner', 'Berliner - 315 x 470 mm (12.4" x 18.5")'), ('broadsheet', 'Broadsheet - 600 x 750 mm (23.5" x 29.5")'), ('tabloid', 'Tabloid - 280 x 430 mm (11.0" x 16.9")')], default='berliner', max_length=100),
        ),
    ]
