# Generated by Django 3.1.3 on 2021-05-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210511_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspaper',
            name='page_size',
            field=models.CharField(choices=[('tabloid', 'Tabloid - 280 x 430 mm (11.0" x 16.9")'), ('berliner', 'Berliner - 315 x 470 mm (12.4" x 18.5")'), ('broadsheet', 'Broadsheet - 600 x 750 mm (23.5" x 29.5")')], default='berliner', max_length=100),
        ),
    ]
