# Generated by Django 3.1.3 on 2021-05-16 03:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_auto_20210515_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='articletask',
            name='article',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.article'),
        ),
        migrations.AlterField(
            model_name='basetask',
            name='assignee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='imagetask',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='page_size',
            field=models.CharField(choices=[('tabloid', 'Tabloid - 280 x 430 mm (11.0" x 16.9")'), ('broadsheet', 'Broadsheet - 600 x 750 mm (23.5" x 29.5")'), ('berliner', 'Berliner - 315 x 470 mm (12.4" x 18.5")')], default='berliner', max_length=100),
        ),
    ]
