# Generated by Django 3.1.3 on 2020-12-29 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201228_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspaper',
            name='columns',
            field=models.CharField(choices=[('2', 2), ('3', 3), ('4', 4), ('5', 5)], default=3, max_length=1),
        ),
    ]
