# Generated by Django 3.1.3 on 2021-05-11 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210511_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='articletask',
            name='newspaper',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.newspaper'),
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='page_size',
            field=models.CharField(choices=[('broadsheet', 'Broadsheet - 600 x 750 mm (23.5" x 29.5")'), ('berliner', 'Berliner - 315 x 470 mm (12.4" x 18.5")'), ('tabloid', 'Tabloid - 280 x 430 mm (11.0" x 16.9")')], default='berliner', max_length=100),
        ),
    ]
