# Generated by Django 3.1.3 on 2020-12-29 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_newspaper_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspaper',
            name='page_size',
            field=models.CharField(choices=[('Berliner - 315 x 470 mm (12.4" x 18.5")', 'berliner'), ('Broadsheet - 600 x 750 mm (23.5" x 29.5")', 'broadsheet'), ('Tabloid - 280 x 430 mm (11.0" x 16.9")', 'tabloid')], default='berliner', max_length=100),
        ),
    ]
