# Generated by Django 3.1.3 on 2021-05-16 06:29

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210516_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texttask',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
        ),
    ]
