# Generated by Django 3.1.3 on 2021-05-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210511_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='adtask',
            name='ad_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='texttask',
            name='article_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
