# Generated by Django 3.1.3 on 2021-01-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201229_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='order',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='page_size',
            field=models.CharField(choices=[('broadsheet', 'Broadsheet - 600 x 750 mm (23.5" x 29.5")'), ('berliner', 'Berliner - 315 x 470 mm (12.4" x 18.5")'), ('tabloid', 'Tabloid - 280 x 430 mm (11.0" x 16.9")')], default='berliner', max_length=100),
        ),
        migrations.AlterOrderWithRespectTo(
            name='article',
            order_with_respect_to='order',
        ),
    ]
